# Generated by Django 5.1.3 on 2024-11-11 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_message_is_read_alter_message_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='content',
            new_name='encrypted_content',
        ),
    ]
